import { type Mail } from '@/components/DashBoard/types'

export const mailData: Mail[] = [
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 1,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 2,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 3,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 4,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 5,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 6,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 7,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 8,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 9,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 10,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 11,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 12,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 13,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 14,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 15,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 16,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 17,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 18,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 19,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 20,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 21,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 22,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 23,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 10,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 24,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 25,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 26,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 27,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 28,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 29,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 31,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 32,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 33,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 34,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 35,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 1,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 2,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 3,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 4,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 5,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 6,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 7,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 8,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 9,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },

  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 26,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 27,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 28,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 29,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 31,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 32,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 33,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 34,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 35,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 1,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 2,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 3,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 4,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 5,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 6,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 7,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 8,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 9,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 10,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 11,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 12,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 13,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 14,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 15,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 16,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 17,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 18,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 19,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 10,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 20,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
]
