import { type UseFormReturn } from 'react-hook-form'
import * as z from 'zod'
import { type ColumnDef } from '@tanstack/react-table'

const addressSchema = z.object({
  address_id: z.string(),
  contact_full_name: z.string(),
  contact_phone_number: z.string(),
  street: z.string(),
  unit_number: z.string(),
  city: z.string(),
  province: z.string().default('Ontario'),
  country: z.string().default('Canada'),
  postal_code: z.string().refine((value) => /^\w\d\w\s?\d\w\d$/.test(value), {
    message: 'Invalid postal code format',
  }),
  instructions: z.string(),
  primary: z.boolean(),
})
export type Address = z.infer<typeof addressSchema>

export const AddressesArraySchema = z.array(addressSchema)

export const profileFormSchema = z.object({
  firstName: z
    .string()
    .min(1, {
      message: 'First name is required',
    })
    .max(60, {
      message: 'First name must be less than 60 characters',
    }),
  lastName: z
    .string()
    .min(1, {
      message: 'Last name is required',
    })
    .max(60, {
      message: 'Last name must be less than 60 characters',
    }),
  primaryAddress: addressSchema,
  role: z.enum(['Admin', 'Platinum', 'Gold', 'Silver', 'Bronze']),
  email: z.string().email({
    message: 'Please enter a valid email address',
  }),
  additionalAddress: z.array(addressSchema).optional(),
})
type UserInfoBaseWithoutPrimaryAddress = Omit<
  z.infer<typeof profileFormSchema>,
  'primaryAddress'
>
type UserInfoBase = Omit<UserInfoBaseWithoutPrimaryAddress, 'additionalAddress'>
export type UserInfo = UserInfoBase & {
  primaryAddress: Address
  additionalAddress?: Address[]
}
export type EditProfileFormPropsType = {
  form: UseFormReturn<{
    firstName: string
    lastName: string
    primaryAddress: {
      streetNumber: number | string
      streetName: string
      city: string
      province: string
      postal: string
      apartmentUnitNumber?: string | undefined
    }
    role: 'Admin' | 'Platinum' | 'Gold' | 'Silver' | 'Bronze'
    email: string
    additionalAddress:
      | {
          streetNumber: number | string
          streetName: string
          city: string
          province: string
          postal: string
          apartmentUnitNumber?: string | undefined
        }[]
      | undefined
  }>
  onSubmit: (values: UserInfo) => void
}
export type Mail = {
  id: string
  email: string
  message: string
  pickupAddress: Address
  deliveryAddress: Address
  retrunDate: string
  amount: number
  shippingStatus: 'Delivered' | 'In Transit' | 'Pending' | 'Error'
}
export type InboxDataTablePropsType = {
  data: Mail[]
  columns: ColumnDef<Mail>[]
}
export type ProfilePropsType = {
  userInfo: UserInfo
  setUserInfo: React.Dispatch<React.SetStateAction<UserInfo>>
}

const PackageDetailSchema = z.object({
  attachment: z.string().optional(),
  label_type: z.string(),
  description: z.string(),
})

const PickupDetailsSchema = z.object({
  full_name: z.string(),
  phone_number: z.string(),
  street: z.string(),
  unit_number: z.string(),
  city: z.string(),
  province: z.string().default('Ontario'),
  country: z.string().default('Canada'),
  postal_code: z.string().refine((value) => /^\w\d\w\s?\d\w\d$/.test(value), {
    message: 'Invalid postal code format',
  }),
  instructions: z.string(),
  pickup_date: z.date(),
})

const PackageDetailsArraySchema = z.array(PackageDetailSchema)

const OrderDetailsSchema = z.object({
  total_cost: z.number(),
  promo_code: z.string(),
  pickup_date: z.date(),
  pickup_method: z.string(),
  total_packages: z.number(),
  extra_packages_included: z.number(),
  package_details: PackageDetailsArraySchema,
  pickup_details: PickupDetailsSchema,
})

const ClientDetailsSchema = z.object({
  first_name: z.string(),
  last_name: z.string(),
  subscription: z.string(),
  subscription_expiry_date: z.date().optional(),
  email: z.string(),
  phone_number: z.string(),
  payment_type: z.string(),
  addresses: AddressesArraySchema,
})

const OrdersCollectionSchema = z.object({
  id: z.string(), // Auto-generated by MongoDB
  order_number: z.string(), // System-generated
  order_date: z.date(),
  status: z.string(),
  order_details: OrderDetailsSchema,
  client_details: ClientDetailsSchema,
})
export type Order = z.infer<typeof OrdersCollectionSchema>

export type ModalPropsType = {
  isOpen: boolean
  setIsOpen: () => void
}
export type LeadData = {
  fullName: string
  postalCode: string
  email: string
}
